aggregate(image_proportion ~ Genre.Updated, gogh, median)
aggregate(image_proportion ~ Genre_Updated, gogh, median)
colnames(gogh)
aggregate(image_proportion ~ Genre, gogh, median)
table(aggregate(image_proportion ~ Genre, gogh, median))
aggregate(image_proportion ~ Genre, gogh, median)
aggregate(image_proportion ~ Genre.UPDATED, gogh, median)
colnames(gogh)
aggregate(image_proportion ~ Genre_gen, gogh, median)
plot(gogh$image_proportion, gogh$Genre)
plot(gogh$Genre, gogh$image_proportion)
plot(gogh$Genre, gogh$image_proportion, las=2)
plot(gogh$Genre.UPDATED, gogh$image_proportion, las=2)
plot(gogh$Genre_gen, gogh$image_proportion, las=2)
plot(gogh$Genre.UPDATED, gogh$image_proportion, las=2)
plot(gogh$Genre_gen, gogh$image_proportion, las=2)
library(ggplot)
library(ggplot2)
ggplot
str(gogh)
head(gogh,5)
gogh$Title
head(gogh,5)
table(gogh$Genre)
table(gogh$Genre.UPDATED)
table(gogh$Genre_gen)
gogh[which(gogh$Genre_gen == 'other')]
gogh[which(gogh$Genre_gen == 'other'),]
gogh[which(gogh$Genre_gen == 'other'),]$Genre
table(gogh$Genre_gen)
gogh[which(gogh$Genre_gen == 'other'),]$Genre.UPDATED
colnames(gogh)
plot(gogh$Month, gogh$Genre_gen)
plot(gogh$Genre_gen, gogh_Month)
plot(gogh$Genre_gen, gogh$Month)
plot(gogh$Genre_gen, gogh$Month, las=2)
plot(gogh$Genre_gen, gogh$Month, las=3)
plot(gogh$Genre_gen, gogh$Month, las=4)
plot(gogh$Genre_gen, gogh$Month, las=1)
plot(gogh$Genre_gen, gogh$Month, las=0)
plot(gogh$Genre_gen, gogh$Month, las=2)
gogh_other <- gogh[which(gogh$Genre_gen == 'other'),]
plot(gogh_other$Genre.UPDATED, gogh_other$Month, las=2)
gogh_other[which(gogh_other$Genre.UPDATED == 'town'),]
gogh_other[which(gogh_other$Genre.UPDATED == 'town '),]
gogh_other[which(gogh_other$Genre.UPDATED == ' town'),]
str(gogh_other)
gogh_other$Genre_gen
gogh_other$Genre.UPDATED
plot(gogh_other$Genre.UPDATED, gogh_other$Month, las=2)
gogh_other$Genre.UPDATED
gogh_other$Genre
plot(gogh_other$Genre, gogh_other$Month, las=2)
gogh$Month[which(gogh$Genre == 'nude'),]
gogh$Month[which(gogh$Genre == 'nude')]
aggregate(Genre_gen ~ Label_Place, gogh, sum())
aggregate(Genre_gen ~ Label_Place, gogh, "sum()")
aggregate(Genre_gen ~ Label_Place, gogh, sum())
aggregate(Genre_gen ~ Label_Place, gogh, function(x) sum(x))
aggregate(Genre_gen ~ Label_Place, data=gogh, FUN=function(x) length(unique(x))
)
aggregate(Genre_gen ~ Label_Place, data=gogh, FUN=function(x) length(x)
)
aggregate(Genre_gen ~ Label_Place, data=gogh, FUN=function(x) length(x))
table(gogh$Label_Place, gogh$Genre_gen)
table(gogh$Genre_gen, gogh$Label_Place)
plot(gogh$Genre_gen, gogh$image_proportion, las=2)
ggplot
ggplot(gogh, aes(factor(Genre_gen))
)
ggplot(gogh, aes(factor(Genre_gen))) + geom_bar9)
ggplot(gogh, aes(factor(Genre_gen))) + geom_bar()
ggplot(gogh, aes(factor(x=Genre_gen,y=image_proportion))) + geom_point()
ggplot(gogh, aes(x=Genre_gen,y=image_proportion)) + geom_point()
ggplot(gogh, aes(x=Genre_gen,y=image_proportion)) + geom_point(alpha=1/2)
ggplot(gogh, aes(x=Genre_gen,y=image_proportion)) + geom_point(alpha=1/4)
ggplot(gogh, aes(x=Genre_gen,y=image_proportion)) + geom_point(alpha=1/10)
ggplot(gogh, aes(x=Genre_gen,y=image_proportion)) + geom_point(alpha=1/5)
colnames(gogh)
reorder
reorder(gogh$Genre_gen, gogh$image_proportion, median)
colnames(gogh)
head(gogh, 3)
range(gogh$brightness_median)
range(gogh$saturation_median)
range(gogh$hue_median)
hsv
hsv()
hsv(13, 244, 235)
hsv(0.1, 0.3, 0.2)
colors()
hsv(0.1, 0.3, 0.2)
range(gogh$hue_median)
gogh$hsv <- hsv((gogh$hue_median/255), (gogh$saturation_median/255), (gogh$brightness_median/255))
head(gogh$hsv, 10)
ggplot(gogh, aes(x=Genre_gen,y=image_proportion)) + geom_point(alpha=1/10)
ggplot(gogh, aes(x=Genre_gen,y=image_proportion)) + geom_point(colour=hsv, alpha=1/5)
ggplot(gogh, aes(x=Genre_gen,y=image_proportion)) + geom_point(colour=gogh$hsv, alpha=1/5)
ggplot(gogh, aes(x=Genre_gen,y=image_proportion)) + geom_point(colour=gogh$hsv, alpha=1/2)
ggplot(gogh, aes(x=Genre_gen,y=image_proportion)) + geom_point(colour=gogh$hsv, alpha=1/4)
ggplot(gogh, aes(x=Genre_gen,y=image_proportion)) + geom_point(colour=gogh$hsv, alpha=1/3)
ggplot(gogh, aes(x=Genre_gen,y=image_proportion)) + geom_point(colour=gogh$hsv, size=4, alpha=1/4)
ggplot(gogh, aes(x=Genre_gen,y=image_proportion)) + geom_point(colour=gogh$hsv, size=4, alpha=1/2)
ggplot(gogh, aes(x=Genre_gen,y=image_proportion)) + geom_point(colour=gogh$hsv, size=4, alpha=1/4)
ggplot(gogh, aes(x=image_proportion,y=Genre_gen)) + geom_point(colour=gogh$hsv, size=4, alpha=1/4)
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4)
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion),colour=hsv)) + geom_point(size=4, alpha=1/4)
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4)
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, fill=1/4)
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, fill=1)
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, fill=1/100)
range(gogh$hue_stdev)
range(gogh$saturation_stdev)
range(gogh$brightness_stdev)
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=(gogh$hue_stdev/255))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4)
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme(bw)
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_bw()
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4)
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_bw()
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_void()
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_classic()
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_minimal()
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light()
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_bw()
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light()
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_bw()
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light()
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_linedraw()
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light()
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="Courier")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="Helvetica")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="Open Sans")
fonts()
font()
fonts
font
names(pdfFonts())
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="Korea1")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="serif")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="mono")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="AvantGarde")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="Bookman")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="Courier")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="Helvetica")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="Palatino")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="NimbusMon")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="Nimbus")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="NimbusSan")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="GB1")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="CNS1")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="Arial")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="ArialMT")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="Arial")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="Sans")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="Arial")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="Helvetica")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="Helvetica-Narrow")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans")
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans", aspect_ratio=1)
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans", aspect.ratio=1)
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans") + theme(aspect.ratio=1)
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(ylim = c(0, 2.5))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0, 2.5))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.5, 2))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0, 2))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0, 2.4))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.1))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.2, 2.1))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.05, 2.1))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.1))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.2))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.1))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.4))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.3))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.2))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/4) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.1))
colnames(gogh)
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/5) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.1))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/5, stroke=0) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.1))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/5, stroke=5) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.1))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=4, alpha=1/5, stroke=1) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.1))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=10, alpha=1/5, stroke=0) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.1))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=5, alpha=1/5, stroke=0) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.1))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(colour=gogh$hsv, size=5, alpha=1/4, stroke=0) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.1))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(size=5, alpha=1/4, stroke=0) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.1))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(size=5, alpha=1/10, stroke=0) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.1))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(size=5, alpha=1/100, stroke=0) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.1))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(size=5, alpha=1/20, stroke=0) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.1))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(size=5, alpha=1/12, stroke=0) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.1))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(size=5, alpha=1/8, stroke=0) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.1))
ggplot(gogh, aes(x=image_proportion,y=reorder(Genre_gen, image_proportion))) + geom_point(size=5, alpha=1/10, stroke=0) + theme_light(base_family="sans") + theme(aspect.ratio=1) + coord_cartesian(xlim = c(0.1, 2.1))
ggplot(gogh, aes(x=Year_Month, y=hsv))
ggplot(gogh, aes(x=Year_Month, y=hsv)) + geom_point(size=5, alpha=1/20, stroke=0)
ggplot(gogh, aes(x=Year_Month, y=hsv)) + geom_point(color=gogh$hsv, size=5, alpha=1/20, stroke=0)
ggplot(gogh, aes(x=Year_Month, y=hsv)) + geom_point(color=gogh$hsv, size=5, alpha=1/40, stroke=0)
ggplot(gogh, aes(x=Year_Month, y=hsv)) + geom_point(color=gogh$hsv, size=5, alpha=1/4, stroke=0)
ggplot(gogh, aes(x=Label_Place, y=Season)) + geom_point(color=gogh$hsv, size=5, alpha=1/4, stroke=0)
ggplot(gogh, aes(x=Label_Place, y=hsv)) + geom_point(color=gogh$hsv, size=5, alpha=1/4, stroke=0)
ggplot(gogh, aes(x=Year_Month, y=hsv)) + geom_point(color=gogh$hsv, size=5, alpha=1/40, stroke=0)
ggplot(gogh, aes(x=Year_Month, y=hsv)) + geom_point(color=gogh$hsv, size=5, alpha=1/4, stroke=0)
ggplot(gogh, aes(x=Year_Month, y=hsv)) + geom_point(color=gogh$hsv, size=5, alpha=1/4, stroke=0) + theme(axis.text.y = element.blank())
ggplot(gogh, aes(x=Year_Month, y=hsv)) + geom_point(color=gogh$hsv, size=5, alpha=1/4, stroke=0) + theme(axis.text.y = element_blank())
ggplot(gogh, aes(x=Year_Month, y=hsv)) + geom_point(color=gogh$hsv, size=5, alpha=1/4, stroke=0) + theme(axis.text.y = element_blank(), axis.line=element_blank())
ggplot(gogh, aes(x=Year_Month, y=hsv)) + geom_point(color=gogh$hsv, size=5, alpha=1/4, stroke=0) + theme(axis.text.y = element_blank(), axis.ticks=element_blank())
ggplot(gogh, aes(x=Year_Month, y=hsv)) + geom_point(color=gogh$hsv, size=5, alpha=1/4, stroke=0) + theme_blank()
ggplot(gogh, aes(x=Year_Month, y=hsv)) + geom_point(color=gogh$hsv, size=5, alpha=1/4, stroke=0) + theme_minimal()
ggplot(gogh, aes(x=Year_Month, y=hsv)) + geom_point(color=gogh$hsv, size=5, alpha=1/4, stroke=0) + theme_minimal() + theme(axis.ticks=element_blank())
ggplot(gogh, aes(x=Year_Month, y=hsv)) + geom_point(color=gogh$hsv, size=5, alpha=1/4, stroke=0) + theme_minimal() + theme(axis.ticks=element_blank(), axis.text.y=element.blank())
ggplot(gogh, aes(x=Year_Month, y=hsv)) + geom_point(color=gogh$hsv, size=5, alpha=1/4, stroke=0) + theme_minimal() + theme(axis.ticks=element_blank(), axis.text.y=element_blank())
history()
savehistory()
gogh <- read.delim("van_Gogh_genres.txt")
library(ggplot2)
slp <- data.frame(table(gogh$Season, gogh$Label_Place))
slp
colnames(slp) <- c("Season", "Label_Place", "Freq")
ggplot(slp, aes(x=Label_Place, y=Season, fill=Freq)) + geom_area()
j <- 1
for (i in 1:20) {
slp$Titles[i] <- toString(gogh[ which(gogh$Season == switch((i%%4)+1, "winter", "fall", "spring", "summer") & gogh$Label_Place == switch((j%%5)+1, "5_Auvers-sur-Oise", "1_Early", "2_Paris", "3_Arles", "4_Saint-Remy-de-Provence_asylum")), ]$Title)
if (i %% 4 == 0) j <- j + 1
}
slp
slp$Season <- factor(slp$Season, levels=c("spring", "summer", "fall", "winter"))
ggplot(slp)+facet_grid(Season ~ Label_Place, switch='both') + theme(strip.background = element_blank(), strip.text.y=element_text(angle=180))
base <- ggplot(slp)+facet_grid(Season ~ Label_Place, switch='both') + theme(strip.background = element_blank(), strip.text.y=element_text(angle=180))
base + annotation_raster("1_yearmonth-histodot.png", 2,3,3,4)
library(png)
install.packages(png)
install.packages('png')
library(png)
library(grid)
img <- readPNG(system.file("img", "1_yearmonth-histodot.png", package="png"))
img <- readPNG(system.file("img", "./1_yearmonth-histodot.png", package="png"))
png
readPNG
?readPNG
system.file
img <- readPNG("1_yearmonth-histodot.png")
img
g <- rasterGrob(img, interpolate=TRUE)
qplot(1:10, 1:10, geom="blank") +
  annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
  geom_point()
library(ggplot2)
library(wordcloud)
slp
temp <- slp$Titles[1]
temp
temp.list <- strsplit(temp, "\\W+", perl=TRUE)
temp.vect <- unlist(temp.list)
wordcloud(temp.vect, min.freq=2, rot.per=0, max.words=50, vfont=c("serif","bold"))
?png
png("cloud1.png", 800, 800)
?png
ggsave("cloud1.pdf", width=10, height=10, units="cm")
temp <- data[i]
temp.list <- strsplit(temp, "\\W+", perl=TRUE)
temp.vect <- unlist(temp.list)
wordcloud(temp.vect, min.freq=2, rot.per=0, max.words=50, vfont=c("serif","bold"))
makecloud <- function(data, i) {
temp <- data[i]
temp.list <- strsplit(temp, "\\W+", perl=TRUE)
temp.vect <- unlist(temp.list)
wordcloud(temp.vect, min.freq=2, rot.per=0, max.words=50, vfont=c("serif","bold"))
}
makecloud(slp$Titles, 1)
makecloud(slp$Titles, 1)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 3)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 3)
makecloud <- function(data, i) {
temp <- data[i]
temp.list <- strsplit(temp, "\\W+", perl=TRUE)
temp.vect <- unlist(temp.list)
temp.vect <- temp.vect[-which(is.element(substr(temp.vect, 1, 1), letters))]
temp.vect <- temp.vect[-which(is.element(temp.vect, c("L", "La", "The", "A")))]
wordcloud(temp.vect, min.freq=2, rot.per=0, max.words=50, vfont=c("serif","bold"))
}
makecloud(slp$Titles, 1)
makecloud(slp$Titles, 1)
makecloud(slp$Titles, 1)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 2)
makecloud(slp$Titles, 3)
makecloud(slp$Titles, 3)
makecloud(slp$Titles, 3)
makecloud(slp$Titles, 4)
makecloud(slp$Titles, 4)
makecloud(slp$Titles, 4)
makecloud(slp$Titles, 4)
makecloud(slp$Titles, 4)
makecloud(slp$Titles, 4)
makecloud(slp$Titles, 4)
makecloud(slp$Titles, 4)
makecloud(slp$Titles, 4)
makecloud(slp$Titles, 4)
makecloud(slp$Titles, 4)
makecloud(slp$Titles, 4)
makecloud(slp$Titles, 4)
makecloud(slp$Titles, 5)
makecloud(slp$Titles, 5)
makecloud(slp$Titles, 5)
makecloud(slp$Titles, 5)
makecloud(slp$Titles, 5)
makecloud(slp$Titles, 6)
makecloud(slp$Titles, 6)
makecloud(slp$Titles, 6)
makecloud(slp$Titles, 6)
makecloud(slp$Titles, 6)
makecloud(slp$Titles, 6)
makecloud(slp$Titles, 6)
makecloud(slp$Titles, 6)
makecloud(slp$Titles, 6)
makecloud(slp$Titles, 6)
makecloud(slp$Titles, 6)
makecloud(slp$Titles, 6)
makecloud(slp$Titles, 7)
makecloud(slp$Titles, 7)
makecloud(slp$Titles, 7)
makecloud(slp$Titles, 7)
makecloud(slp$Titles, 8)
makecloud(slp$Titles, 8)
makecloud(slp$Titles, 8)
makecloud(slp$Titles, 8)
makecloud(slp$Titles, 8)
makecloud(slp$Titles, 8)
makecloud(slp$Titles, 9)
makecloud(slp$Titles, 9)
makecloud(slp$Titles, 9)
makecloud(slp$Titles, 9)
makecloud(slp$Titles, 9)
makecloud(slp$Titles, 9)
makecloud(slp$Titles, 10)
makecloud(slp$Titles, 10)
makecloud(slp$Titles, 11)
makecloud(slp$Titles, 11)
makecloud(slp$Titles, 11)
makecloud(slp$Titles, 11)
makecloud(slp$Titles, 11)
makecloud(slp$Titles, 11)
makecloud(slp$Titles, 11)
makecloud(slp$Titles, 11)
makecloud(slp$Titles, 12)
makecloud(slp$Titles, 12)
makecloud(slp$Titles, 12)
makecloud(slp$Titles, 13)
makecloud(slp$Titles, 13)
makecloud(slp$Titles, 13)
makecloud(slp$Titles, 14)
makecloud(slp$Titles, 14)
makecloud(slp$Titles, 14)
makecloud(slp$Titles, 14)
makecloud(slp$Titles, 14)
makecloud(slp$Titles, 14)
makecloud(slp$Titles, 14)
makecloud(slp$Titles, 14)
makecloud(slp$Titles, 15)
makecloud(slp$Titles, 15)
makecloud(slp$Titles, 15)
makecloud(slp$Titles, 15)
makecloud(slp$Titles, 15)
makecloud(slp$Titles, 15)
makecloud(slp$Titles, 15)
makecloud(slp$Titles, 15)
makecloud(slp$Titles, 15)
makecloud(slp$Titles, 15)
makecloud(slp$Titles, 15)
makecloud(slp$Titles, 15)
makecloud(slp$Titles, 15)
makecloud(slp$Titles, 15)
makecloud(slp$Titles, 15)
makecloud(slp$Titles, 16)
makecloud(slp$Titles, 16)
makecloud(slp$Titles, 16)
makecloud(slp$Titles, 16)
makecloud(slp$Titles, 16)
makecloud(slp$Titles, 17)
makecloud(slp$Titles, 18)
makecloud(slp$Titles, 18)
makecloud(slp$Titles, 18)
makecloud(slp$Titles, 18)
makecloud(slp$Titles, 18)
makecloud(slp$Titles, 18)
makecloud(slp$Titles, 18)
makecloud(slp$Titles, 18)
makecloud(slp$Titles, 18)
makecloud(slp$Titles, 18)
makecloud(slp$Titles, 18)
makecloud(slp$Titles, 18)
makecloud(slp$Titles, 18)
makecloud(slp$Titles, 18)
makecloud(slp$Titles, 19)
makecloud(slp$Titles, 19)
makecloud(slp$Titles, 19)
makecloud(slp$Titles, 19)
makecloud(slp$Titles, 19)
makecloud(slp$Titles, 19)
makecloud(slp$Titles, 19)
makecloud(slp$Titles, 19)
makecloud(slp$Titles, 19)
makecloud(slp$Titles, 20)
slp$Season[1]
paste("cloud", toString(1), ".png", sep="")
img1 <- readPNG("cloud1.png")
img2 <- readPNG("cloud2.png")
img3 <- readPNG("cloud3.png")
img4 <- readPNG("cloud4.png")
img5 <- readPNG("cloud5.png")
img6 <- readPNG("cloud6.png")
img7 <- readPNG("cloud7.png")
img8 <- readPNG("cloud8.png")
img9 <- readPNG("cloud9.png")
img10 <- readPNG("cloud10.png")
img11 <- readPNG("cloud11.png")
img12 <- readPNG("cloud12.png")
img13 <- readPNG("cloud13.png")
img14 <- readPNG("cloud14.png")
img15 <- readPNG("cloud15.png")
img16 <- readPNG("cloud16.png")
img18 <- readPNG("cloud18.png")
img19 <- readPNG("cloud19.png")
g1 <- rasterGrob(img1, interpolate=TRUE)
g2 <- rasterGrob(img2, interpolate=TRUE)
g3 <- rasterGrob(img3, interpolate=TRUE)
g4 <- rasterGrob(img4, interpolate=TRUE)
g5 <- rasterGrob(img5, interpolate=TRUE)
g6 <- rasterGrob(img6, interpolate=TRUE)
g7 <- rasterGrob(img7, interpolate=TRUE)
g8 <- rasterGrob(img8, interpolate=TRUE)
g9 <- rasterGrob(img9, interpolate=TRUE)
g10 <- rasterGrob(img10, interpolate=TRUE)
g11 <- rasterGrob(img11, interpolate=TRUE)
g12 <- rasterGrob(img12, interpolate=TRUE)
g13 <- rasterGrob(img13, interpolate=TRUE)
g14 <- rasterGrob(img14, interpolate=TRUE)
g15 <- rasterGrob(img15, interpolate=TRUE)
g16 <- rasterGrob(img16, interpolate=TRUE)
g18 <- rasterGrob(img18, interpolate=TRUE)
g19 <- rasterGrob(img19, interpolate=TRUE)
groupg = c(g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14, g15, g16, g18, g19)
rm(img1)
rm(img2)
rm(img3)
rm(img4)
rm(img5)
rm(img6)
rm(img7)
rm(img8)
rm(img9)
rm(img10)
rm(img11)
rm(img12)
rm(img13)
rm(img14)
rm(img15)
rm(img16)
rm(img18)
rm(img19)
base
base <- ggplot(slp) + facet_grid(Season ~ Label_Place, switch = "both") + theme(strip.background = element_blank())
base
slp
plot.new()
list()
ls()
ggplot
ggplot()
system.time
system.time()
base <- ggplot(df, aes(x, y)) +
  geom_blank() +
  theme_bw()
base
df <- data.frame(x = 1:10, y = 1:10)
base <- ggplot(df, aes(x, y)) +
  geom_blank() +
  theme_bw()
base
print(base)
ls()
rm(img1)
rm(img2)
rm(img3)
rm(img4)
rm(img5)
rm(img6)
rm(img7)
rm(img8)
rm(img9)
rm(img10)
rm(img11)
rm(img12)
rm(img13)
rm(img14)
rm(img15)
rm(img16)
rm(img17)
rm(img18)
rm(img19)
rm(img)
ls()
rm(g)
base
savehistory("images")
